global:
  resolve_timeout: 1m

route:
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - send_resolved: true
        username: 'PrometheusBot'
        channel: '#healthpower-alerts'
        api_url: 'https://hooks.slack.com/services/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'

