global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: '${SLACK_ALERT_WEBHOOK}' # deploy.yml에서 넣음
        channel: '#your-alert-channel'
        send_resolved: true
