networks:
  bg:
    driver: bridge

services:
  spring-blue:
    build:
      context: ./spring-blue
      dockerfile: ../../Dockerfile
    container_name: spring-blue
    environment:
      SPRING_PROFILES_ACTIVE: prod
      LOGSTASH_HOST: ${LOGSTASH_HOST}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./spring-blue:/app
    expose: ["8080"]

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"]
      interval: 10s
      start_period: 60s
      retries: 10
    networks: [bg]

  spring-green:
    container_name: spring-green
    image: eclipse-temurin:21-jre
    command: ["java","-jar","/app/app.jar"]
    environment:
      - CONTAINER_COLOR=green
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./spring-green:/app
    expose: ["8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      retries: 5
    networks: [bg]

  nginx:
    container_name: nginx-proxy
    image: nginx:1.27-alpine
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - spring-blue
      - spring-green
    networks: [bg]
