# ./prometheus/prometheus.yml
global:
  scrape_interval: 15s

rule_files:

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['healthpower-app:8080']

