name: Build & Push image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env: # ← job env 블록
      AWS_REGION: ap-northeast-2
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

    steps:
      - uses: actions/checkout@v4

      # 새로 추가 – gradlew 에 실행권한 부여
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 1) JAR 빌드 (Gradle 예시)
      - name: Build jar
        run: ./gradlew clean bootJar

      # 2) AWS 로그인
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # 3) Docker build & push
      - name: Build and push
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REGISTRY/healthpower:$IMAGE_TAG .
          docker push  $ECR_REGISTRY/healthpower:$IMAGE_TAG
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        id: build
